# Generated by Django 6.0.6 on 2026-06-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('confirmed', 'Confermato'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('canceled', 'Annullato')], default='pending', max_length=50, verbose_name='Stato')),
                ('shipping_address', models.CharField(max_length=250, verbose_name='Indirizzo')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Città')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='CAP')),
                ('shipping_province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nome Prodotto')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo Unitario')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordini.order', verbose_name='Ordine')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalogo.product', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Riga Ordine',
                'verbose_name_plural': 'Righe Ordini',
            },
        ),
    ]
